# Generated by Django 4.2.13 on 2024-05-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stats', '0001_initial'),
        ('players', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeagueSeason',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_year', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='LeagueWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('actual_stats', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_actual_stats', to='stats.playerstats')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.player')),
                ('projected_stats', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='player_projected_stats', to='stats.playerstats')),
            ],
        ),
        migrations.CreateModel(
            name='DefenseSTWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('start_time', models.DateTimeField()),
                ('actual_stats', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defensest_actual_stats', to='stats.defenseststats')),
                ('defense', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='players.defensest')),
                ('projected_stats', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defensest_projected_stats', to='stats.defenseststats')),
            ],
        ),
    ]
