# Generated by Django 4.2.13 on 2024-05-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('schedule', '0001_initial'),
        ('players', '0002_initial'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='manager',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.teammanager'),
        ),
        migrations.AddField(
            model_name='team',
            name='roster',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.roster'),
        ),
        migrations.AddField(
            model_name='roster',
            name='lineup',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='teams.lineup'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='dst',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dst_lineup', to='players.defensest'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='flex',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='flex_lineup', to='players.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='k',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='k_lineup', to='players.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='league_week',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='schedule.leagueweek'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='qb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='qb_lineup', to='players.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='rb',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rb_lineup', to='players.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='te',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='te_lineup', to='players.player'),
        ),
        migrations.AddField(
            model_name='lineup',
            name='wr',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wr_set', to='players.player'),
        ),
    ]
