# Generated by Django 4.2.13 on 2024-05-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseSTStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.FloatField()),
                ('rushing_attempts', models.PositiveIntegerField()),
                ('passing_attempts', models.PositiveIntegerField()),
                ('receptions', models.PositiveIntegerField()),
                ('field_goal_attempts', models.PositiveIntegerField()),
            ],
        ),
    ]
