# Generated by Django 4.2.13 on 2024-05-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DefenseST',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(blank=True, choices=[('qb', 'Quarter Back'), ('rb', 'Running Back'), ('wr', 'Wide Receiver'), ('te', 'Tight End'), ('k', 'Kicker')], max_length=100, null=True)),
                ('bye_week', models.PositiveIntegerField()),
            ],
        ),
    ]
